# helpnav — browse the help of the tool you have started typing, and land the
# command you picked on the line. Generated by `helpnav shell widgets zsh`;
# edit it there, not here.
# Bind the widget where you know the keymap: bindkey '^X^H' helpnav-widget

# Replaces the line you are on. The tool is the first word already typed, so
# the flow is: type `docker`, press the key, walk the tree, land on
# `docker container ls`.
helpnav-widget() {
  # Split into a named array rather than subscripting the expansion inline: a
  # one-word line collapses back to a scalar there, and [1] on a scalar is the
  # first character, so `uv` would browse a tool called `u`.
  local -a words
  words=(${(z)BUFFER})
  local tool="${words[1]}"
  if [[ -z "$tool" ]]; then
    zle -M "helpnav: type the name of a tool first"
    return
  fi
  local chosen
  # </dev/tty because the widget's stdin is not guaranteed to be the terminal,
  # and a full-screen reader that cannot read keys hangs rather than failing.
  chosen="$(helpnav "$tool" </dev/tty)"
  if [[ -n "$chosen" ]]; then
    BUFFER="$chosen"
    CURSOR=${#BUFFER}
  fi
  # The reader paints over the prompt and does not put it back.
  zle reset-prompt
}
zle -N helpnav-widget

# Loads the next prompt instead, for when the line you are on is worth keeping.
hn() {
  local chosen
  chosen="$(helpnav "$@" </dev/tty)"
  [[ -n "$chosen" ]] && print -z -- "$chosen"
}
